[bindings.kotlin]
package_name = "org.examples.calendar"
cdylib_name = "calendarffi"

[bindings.kotlin.external_packages]
# Map the crate names from [External={name}] into Kotlin package names
clock_ffi = "org.examples.clock"
