[package]
name = "clock_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]
name = "clock_ffi"

[features]
default = ["uniffi/cli"]

[dependencies]
uniffi = { version = "=0.28.0" }

[build-dependencies]
uniffi = { version = "=0.28.0", features = ["build"] }
